from .user import User
from .event import Event
from .message import Message
from .conversation import Conversation
from .participation import Participation
from .group import Group
from .user_group import UserGroup
from .department import Department
from .administrative_staff import AdministrativeStaff
from .teacher import Teacher
from .student import Student
from .parent import Parent
from .parent_student import ParentStudent
from .class_ import Class
from .class_subject import ClassSubject
from .subject import Subject
from .grade import Grade
from .grade_component import GradeComponent
from .student_rnp import StudentRNP
from .reward_punishment import RewardPunishment
from .class_rnp import ClassRNP
from .petition import Petition
